// bant - Bazel Navigation Tool
// Copyright (C) 2024 Henner Zeller <h.zeller@acm.org>
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

#ifndef BANT_SOURCE_LOCATOR_
#define BANT_SOURCE_LOCATOR_

#include <ostream>
#include <string>
#include <string_view>

namespace bant {
// Zero-based line and column.
struct LineColumn {
  int line;
  int col;

  bool operator==(const LineColumn &) const = default;
};

// Print line and column; one-based for easier human consumption.
std::ostream &operator<<(std::ostream &out, LineColumn);

struct LineColumnRange {
  LineColumn start;  // inclusive
  LineColumn end;    // exclusive

  bool operator==(const LineColumnRange &) const = default;
};

std::ostream &operator<<(std::ostream &out, const LineColumnRange &);

struct FileLocation {
  std::string_view filename;
  LineColumnRange line_column_range;
};

std::ostream &operator<<(std::ostream &out, const FileLocation &floc);

// A SourceLocator can return the line-column location inside some content it
// is responsible for. This can typically be inside a file, but can also be
// a fixed location from content that is generated by expression evaluation.
class SourceLocator {
 public:
  virtual ~SourceLocator() = default;

  // Given "text", that must be a substring handled by this locator,
  // return file and location .
  virtual FileLocation GetLocation(std::string_view text) const = 0;

  // Return an expansion of the string view representing the full line the
  // text snippets resides in. Line will be without newline separators.
  // If there is no context known beyond the given text, just returns text.
  virtual std::string_view GetSurroundingLine(std::string_view text) const = 0;

  // Convenience functions.

  // Given the string_view, that must be a substring handled by this locator,
  // format the location of that string view to stream as file.txt:<line>:<col>:
  std::ostream &Loc(std::ostream &out, std::string_view s) const;

  // Same, but instead of writing to stream, returning a string.
  std::string Loc(std::string_view s) const;
};

class FixedSourceLocator : public SourceLocator {
 public:
  // Note: Location (with string_view to filename) must stay valid for the
  // life-time of this object.
  explicit FixedSourceLocator(const FileLocation &location)
      : location_(location) {}

  FileLocation GetLocation(std::string_view text) const final {
    return location_;  // Unconditional fixed location.
  }

  std::string_view GetSurroundingLine(std::string_view text) const final {
    return text;
  }

 private:
  const FileLocation location_;
};

}  // namespace bant
#endif  // BANT_SOURCE_LOCATOR_
