// bant - Bazel Navigation Tool
// Copyright (C) 2024 Henner Zeller <h.zeller@acm.org>
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

// The following is to work around not very cleanly defined system headers
// so that it is not clear to clang-tidy that unistd.h would provide optarg
// and optind and getopt.h provides getopt_long().
// understanding that unistd.h indeed provides getopt(). So let's include
// unistd.h and getopt.h for correctness, and then soothe clang-tidy with decls.
#include <getopt.h>  // IWYU pragma: keep
#include <unistd.h>  // IWYU pragma: keep
extern "C" {
extern char *optarg;  // NOLINT
extern int optind;    // NOLINT
}

#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <map>
#include <memory>
#include <string>
#include <string_view>
#include <system_error>
#include <vector>

#include "absl/container/flat_hash_set.h"
#include "absl/strings/numbers.h"
#include "absl/strings/str_format.h"
#include "absl/time/time.h"
#include "bant/cli-commands.h"
#include "bant/output-format.h"
#include "bant/session.h"
#include "bant/util/stat.h"

// Generated from at compile time from git tag or MODULE.bazel version
#include "bant/generated-build-version.h"
#include "bant/util/filesystem-prewarm-cache.h"
#include "bant/util/filesystem.h"

#define BOLD  "\033[1m"
#define RED   "\033[1;31m"
#define RESET "\033[0m"

// Print version coming from BANT_BUILD_GIT_VERSION that is generated by
// by workspace status extracted from git.
// If that didn't happen (e.g. we're built as part of being a MODULE.bazel
// dependency), use BANT_MODULE_VERSION as secondary source.
static int print_version() {
#ifdef BANT_BUILD_GIT_VERSION
#define RELEVANT_VERSION BANT_BUILD_GIT_VERSION
#elif defined(BANT_MODULE_VERSION)
#define RELEVANT_VERSION BANT_MODULE_VERSION
#else
#define RELEVANT_VERSION "(unknown)"
#endif
  fprintf(stderr,
          "bant v%s <http://bant.build/>\n"
          "Copyright (c) 2024-2026 Henner Zeller. "
          "This program is free software; GPL 3.0.\n",
          RELEVANT_VERSION);
  return EXIT_SUCCESS;
#undef RELEVANT_VERSION
}

static int usage(const char *prog, const char *message, int exit_code) {
  print_version();
  fprintf(stderr, "Usage: %s [options] <command> [bazel-target-pattern...]\n",
          prog);
  fprintf(stderr, R"(Options
    -C <directory> : Change to this project directory first (default = '.')
    -q, --quiet    : Quiet: don't print info messages to stderr.
    -o <filename>  : Instead of stdout, emit command primary output to file.
    -f <format>    : Output format, support depends on command. One of
                   : native (default), s-expr, plist, json, csv
                     Unique prefix ok, so -fs , -fp, -fj or -fc is sufficient.
    -g <regex>,    : 'grep'-filter output with regular expression. Can be
    --grep <regex>   provided multiple times to narrow match ('and' semantics).
                     Matches are highlit with different colors (also see '-O').
    -G <regex>     : Exclude records that match regex (like grep -v)
                     (Long form --exclude-match <regex>)
    -i, --ignore-case  : (with `-g`, `-G`): Treat regex case-insensitively.
    -O, --or        : (with `-g`): 'or' match smentics. Instead of requiring all
                     regexs to match for a record, require at least one of them.
    -r             : Follow dependencies recursively starting from pattern.
                     Without numeric parameter, follows dependencies to the end.
                     An optional parameter allows to limit the nesting depth,
                     e.g. -r2 just follows two levels after the toplevel
                     pattern. Default for most commands is -r5
    -v             : Verbose; print some stats. Multiple times: more verbose.
    -h             : This help.
    --//<option>   : configurable flag attribute to be used in select() and
                     picked up by elaboration (-e) (experimental; does not yet
                     read config_setting(), but flag value is used directly).
    --color=<opt>  : enable colored output. One of "auto", "never", "always"

Commands (unique prefix sufficient):
    %s== Parsing ==%s
    print          : Print rules matching pattern. (-E : only files w/ errors)
                      -a, --all         : print all toplevel items in packages,
                                          not just rules.
                      -e, --elaborate   : elaborate; light eval: expand
                                          variables, concat, some functions etc.
                      -m, --macro-expand: expand macros and elaborate.
                      -g, -i, -O work here and print the whole item on match.
    parse          : Parse all BUILD files from pattern. Follow deps with -r
                     Emit parse errors. Silent otherwise: No news are good news.
                      -v : some stats.
                      -e, -m: same as in print; -vv and -vvv print eval issues.
    %s== Extract facts ==%s (Use -f to choose output format) ==
    workspace      : Print external projects found in WORKSPACE/MODULE.bazel
                     Without pattern: All external projects.
                     With pattern   : Subset referenced by matching targets.
                     → 3 column table: (project, version, path)

    -- Given '-r', the following also follow dependencies recursively --
    list-packages  : List all BUILD files and the package they define
                     → 2 column table: (buildfile, package)
    list-targets   : List BUILD file locations of rules with matching targets
                     → 3 column table: (buildfile:location, ruletype, target)
    list-leafs     : Show only targets not referenced anywhere.
                     → 3 column table: (buildfile:location, ruletype, target)
    list-filegroups: List all filegroups/genrule and the files they provide
                     → 2 column table: (target, file*)
    aliased-by     : List targets and the various aliases pointing to it.
                     → 2 column table: (actual, alias*)
    depends-on     : List cc library targets and the libraries they depend on
                     → 2 column table: (target, dependency*)
    has-dependent  : List cc library targets and the libraries that depend on it
                     → 2 column table: (target, dependent*)
    target-hdrs,   : Print either hdrs, srcs or data mentioned in targets.
    target-srcs,      -P: only if these are non-generated physical files
    target-data       -d duplicates : only files mentioned by multiple targets
                      -u unique     : only files mentioned exactly once.
                     → 2 column table: (filename, target*)
    lib-headers    : Like target-hdrs, but all reachable paths expanded with all
                     combinations of includes = [], include_prefix, etc.
                     So same header can show up multiple times with different
                     paths. This is the relevant list used by dwyu.
                      -r to recurse into dependencies beyond match pattern.
                      -d duplicates: headers provided by multiple targets
                      -u unique:     only headers mentioned exactly once.
                     → 2 column table: (header-filename, cc-library-target*)
    srcs-canonical : Outputs a mapping of all short names to canonical
                     names in projects. There can be multiple short names
                     to a canonical name if project uses `includes = []`
                     constructs.
                      -d duplicates : print only ambiguous mappings.
                      -u unique     : print unambiuous short->canonical
                      -s suppress same: if (left col)==(right col), don't print.
                     → 2 column table: (source, canonical-source*)
    genrule-outputs: Print generated files by genrule()s matching pattern.
                     → 2 column table: (filename, genrule-target)

    %s== Tools ==%s
    dwyu           : DWYU: Depend on What You Use (emit buildozer edit script)
                     Default invocation uses -r4
                      -k strict: emit remove even if # keep comment in line.
                      --allow-bracket-includes: also consider includes that
                        are bracketed instead of quoted (e.g. <zlib.h>
                        instead of "zlib.h")
                        (fix your project to use quotes if you need this)
    canonicalize   : Emit rename edits to canonicalize targets.
    compile-flags  : (experimental) Emit compile flags. Redirect or output with
                     -o compile_flags.txt
    compilation-db : (experimental) Emit compilation db. Redirect or output with
                     -o compile_commands.json
)",
          BOLD, RESET, BOLD, RESET, BOLD, RESET);

  if (message) {
    fprintf(stderr, "\n%s%s%s\n", RED, message, RESET);
  }
  return exit_code;
}

// Bazel custom flag extraction, such as --//foo:bar to be used in selectors.
static void ExtractCustomFlags(int *argc, char *argv[],
                               absl::flat_hash_set<std::string> *result) {
  int out_arg = 1;
  for (int i = 1; i < *argc; ++i) {
    const std::string_view arg = argv[i];
    if (arg.starts_with("--//")) {
      result->emplace(arg.substr(2));
      continue;
    }
    argv[out_arg++] = argv[i];
  }
  *argc = out_arg;
}

static void PossiblyApplyBazelIgnore(bant::Filesystem &fs) {
  std::fstream input(".bazelignore", std::ios::in | std::ios::binary);
  if (!input.good()) return;
  std::string line;
  while (std::getline(input, line)) {
    fs.SetAlwaysReportEmptyDirectory(line);
  }
}

int main(int argc, char *argv[]) {
  // non-nullptr streams if chosen by user.
  std::unique_ptr<std::ostream> user_primary_out;
  std::unique_ptr<std::ostream> user_info_out;

  // Default primary and info outputs.
  std::ostream *primary_out = &std::cout;
  std::ostream *info_out = &std::cerr;
  std::ostream *const error_out = &std::cerr;  // Can not be -q'ed

  bool be_quiet = false;
  const char *context_deps_start_here = nullptr;

  bant::CommandlineFlags flags;
  flags.do_color = isatty(STDOUT_FILENO);

  // Since we're using basic getopt() currently, we've to fish out all the
  // double-dash bazel configs, otherwise getopt() gets confused about unknown
  // options.
  // TODO: replace with better flag handling.
  ExtractCustomFlags(&argc, argv, &flags.custom_flags);

  using bant::OutputFormat;
  static const std::map<std::string_view, OutputFormat> kFormatOutNames = {
    {"native", OutputFormat::kNative}, {"s-expr", OutputFormat::kSExpr},
    {"plist", OutputFormat::kPList},   {"csv", OutputFormat::kCSV},
    {"json", OutputFormat::kJSON},     {"graphviz", OutputFormat::kGraphviz},
  };

  enum LongOptionIds {
    OPT_COLOR = 1000,
    OPT_ALLOW_BRACKET_INC = 1001,
    OPT_GRAPH_AUGMENT = 1002,
  };

  // clang-format off
  // NOLINTBEGIN
  static constexpr struct option long_options[] = {
    { "color",         required_argument, nullptr, OPT_COLOR    },
    { "quiet",         no_argument,       nullptr, 'q'          },
    { "grep",          required_argument, nullptr, 'g'          },
    { "exclude-match", required_argument, nullptr, 'G'          },
    { "ignore-case",   required_argument, nullptr, 'i'          },
    { "or",            required_argument, nullptr, 'O'          },
    { "macro-expand",  no_argument,       nullptr, 'm'          },
    { "elaborate",     no_argument,       nullptr, 'e'          },
    { "directory",     required_argument, nullptr, 'C'          },
    { "allow-bracket-includes", no_argument, nullptr, OPT_ALLOW_BRACKET_INC },
    { "graph-augment", required_argument, nullptr, OPT_GRAPH_AUGMENT },
    //
    { nullptr, 0,                 nullptr, 0                    }};
  // NOLINTEND
  // clang-format on

  int opt;
  int option_index = 0;
  // NOLINTNEXTLINE(misc-include-cleaner)  clang-tidy can't see getopt_long()
  while ((opt = getopt_long(argc, argv, "C:qo:vhaEF:ecbmf:r::Vkg:G:iT:POdus",
                            long_options, &option_index)) != -1) {
    switch (opt) {
    case 'C': {
      std::error_code err;
      std::filesystem::current_path(optarg, err);
      if (err) {
        std::cerr << "Can't change into directory " << optarg << "\n";
        return 1;
      }
      break;
    }

    case 'q':  //
      be_quiet = true;
      user_info_out.reset(new std::ostream(nullptr));
      info_out = user_info_out.get();
      break;

    case 'o':  //
      if (std::string_view(optarg) == "-") {
        primary_out = &std::cout;
        break;
      }
      user_primary_out.reset(new std::fstream(
        optarg, std::ios::out | std::ios::binary | std::ios::trunc));
      if (!user_primary_out->good()) {
        std::cerr << "Could not open '" << optarg << "'\n";
        return 1;
      }
      primary_out = user_primary_out.get();
      break;

    case 'r':
      flags.recurse_dependency_depth = std::numeric_limits<int>::max();
      if (optarg &&
          !absl::SimpleAtoi(optarg, &flags.recurse_dependency_depth)) {
        return usage(argv[0], "-r requires either none or a numeric parameter",
                     EXIT_FAILURE);
      }
      break;

    case 'k': flags.ignore_keep_comment = true; break;
    case 'd':
      flags.duplicate_handling = bant::DuplicateHandling::kOutputOnlyDuplicates;
      break;
    case 'u':
      flags.duplicate_handling = bant::DuplicateHandling::kOutputOnlyUnique;
      break;
    case 's': flags.suppress_same = true; break;

    case 'g': flags.grep_include_expressions.emplace_back(optarg); break;
    case 'G': flags.grep_exclude_expressions.emplace_back(optarg); break;
    case 'O': flags.grep_or_semantics = true; break;
    case 'i':
      flags.regex_case_insesitive = true;
      break;

      // "print" options
    case 'a': flags.print_ast = true; break;
    case 'E': flags.print_only_errors = true; break;
    case 'F': flags.direct_filename = optarg; break;
    case 'b':  // legacy for 'builtin' macro
      fprintf(stderr, "FYI: '-b' option is renamed '-m' (for macro)\n\n");
      [[fallthrough]];
    case 'm':  // better name 'm' for macro as we now have .bant-macros
      flags.elaborate = flags.bant_macro_expand = true;
      break;
    case 'e': flags.elaborate = true; break;
    case 'f': {
      auto found = kFormatOutNames.lower_bound(optarg);
      if (found == kFormatOutNames.end() || !found->first.starts_with(optarg)) {
        return usage(argv[0], "invalid -f format", EXIT_FAILURE);
      }
      flags.output_format = found->second;
    } break;
    case 'T':
      if (!absl::SimpleAtoi(optarg, &flags.io_threads)) {
        return usage(argv[0], "-T needs a numeric parameter", EXIT_FAILURE);
      }
      break;
    case 'P': flags.only_physical_files = true; break;
    case 'v': flags.verbose++; break;  // More -v, more detail.
    case 'V': return print_version();
    case OPT_COLOR: {
      const std::string_view o(optarg);
      if (o == "auto") {
        flags.do_color = isatty(STDOUT_FILENO);
      } else if (o == "never") {
        flags.do_color = false;
      } else if (o == "always") {
        flags.do_color = true;
      } else {
        fprintf(stderr,
                "--color should be one of 'auto', "
                "'never', or 'always'\n");
        return EXIT_FAILURE;
      }
    } break;
    case OPT_ALLOW_BRACKET_INC: flags.allow_bracket_includes = true; break;
    case OPT_GRAPH_AUGMENT: {
      context_deps_start_here = optarg;
      flags.graph_deps.emplace_back(optarg);
    } break;
    default: return usage(argv[0], nullptr, EXIT_SUCCESS);
    }
  }

  // TODO: the various scoped areas below look like they actually want
  // to be functions.

  bant::Session session(primary_out, info_out, error_out, flags);
  absl::Duration runtime;
  bool did_prewarm;
  bant::CliStatus result;

  {
    const bant::ScopedTimer timer(&runtime);
    // Prepare filesystem
    did_prewarm = bant::FilesystemPrewarmCacheInit(session, argc, argv);
    bant::Filesystem &fs = bant::Filesystem::instance();
    PossiblyApplyBazelIgnore(fs);

    std::vector<std::string_view> positional_args;
    for (int i = optind; i < argc; ++i) {
      const char *const arg = argv[i];
      if (context_deps_start_here != nullptr && arg > context_deps_start_here) {
        // after --graph-augment, regular positional args are finished and
        // everything is just considred a graph augmentation pattern.
        // Note, we assume that strings in argv are allocated consecutively.
        flags.graph_deps.emplace_back(arg);
      } else {
        positional_args.emplace_back(arg);
      }
    }

    result = RunCliCommand(session, positional_args);
    if (result == bant::CliStatus::kExitCommandlineClarification) {
      session.error() << "\n\n";  // A bit more space to let message stand out.
      return usage(argv[0], nullptr, static_cast<int>(result));
    }
  }

  const bool unusually_long_runtime = (runtime > absl::Seconds(30));
  if (flags.verbose || (unusually_long_runtime && !be_quiet)) {
    // If verbose explicitly chosen, we want to print this even if -q.
    // So not to info_out (which is null-stream then), but std::cerr

    if (unusually_long_runtime) {
      if (flags.do_color) std::cerr << "\033[35m";  // magenta
      std::cerr
        << "This took unusually long. Here is a breakdown (also with -v):\n";
      if (!did_prewarm) {
        std::cerr << "Consider filesystem prewarm cache enabling with\n\n"
                  << "mkdir ~/.cache/bant\n\n";
      }
      if (flags.do_color) std::cerr << "\033[0m";
    }

    for (const std::string_view subsystem : session.stat_keys()) {
      std::cerr << absl::StrFormat(
        "%-32s %s\n", subsystem,
        session.stat(subsystem)->ToString(flags.do_color));
    }
    std::cerr << "Total walltime " << runtime << "\n";
  }
  return static_cast<int>(result);
}
