// bant - Bazel Navigation Tool
// Copyright (C) 2024 Henner Zeller <h.zeller@acm.org>
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

#ifndef BANT_PROJECT_INDEXING_
#define BANT_PROJECT_INDEXING_

#include <cstdlib>
#include <optional>
#include <ostream>
#include <string>
#include <string_view>
#include <vector>

#include "absl/container/btree_set.h"
#include "bant/frontend/parsed-project.h"
#include "bant/session.h"
#include "bant/types-bazel.h"
#include "bant/types.h"
#include "bant/workspace.h"

// Create various useful indexes and collections from the project.

namespace bant {

// Map describing what file has been provided by which target.
// This should be a 1:1 relationship. However, some libraries have been observed
// to provide the same hader. So, OneToN it is there..
using ProvidedFromTarget = OneToOne<std::string, BazelTarget>;
using ProvidedFromTargetSet = OneToNSet<std::string, BazelTarget>;

// An inverse map for files provided by bazel target yielding files. Used for
// {genrule,filegroup} -> file. The string-view points to original source.
using TargetProvidedFiles = OneToNSet<BazelTarget, std::string_view>;

// Header to canonical header.
using HeaderToCanonicalHeader = OneToNSet<std::string, std::string>;

// Givent the "project", creates a mapping of all headers that are exported by
// cc_library() targets to their respective targets. If a header can be reached
// multiple ways (e.g. due to include = [] directives), they are also part
// of the keys.
// If "suffix_index" is set, output is compatible with FindBySuffix()
ProvidedFromTargetSet ExtractExpandedHeaderToLibMapping(
  const ParsedProject &project, std::ostream &info_out,
  bool suffix_index = false);

// Create a mapping of .proto source files to their providing proto_library()
// targets. Used for proto-level DWYU checking (import statements in .proto
// files vs deps of proto_library rules).
// If "suffix_index" is set, output is compatible with FindBySuffix().
ProvidedFromTargetSet ExtractProtoToProtoLibMapping(
  const ParsedProject &project, std::ostream &info_out,
  bool suffix_index = false);

// Provides a mapping of short forms of headers (due to `includes = []`)
// and maps them to their canonical form.
// In well-defined projects that stay away from `includes = []` there are only
// canonical start-from-project-root headers that are identical to thier
// canonical ones.
HeaderToCanonicalHeader CanonicalHeaderMapping(const ParsedProject &project,
                                               std::ostream &info_out);

// Unlike the Expanded*, this is much simpler, as we don't deal with multiple
// search paths. Just extract the mentioned component. If "only_physical_files"
// is on, only emit them if these are files in the filesystem (unlike
// generated files or target names).
enum class ExtractComponent {
  kSrcs,
  kHdrs,
  kData,
};
ProvidedFromTargetSet ExtractComponentToTargetMapping(
  const ParsedProject &project, ExtractComponent which,
  bool only_physical_files, std::ostream &info_out);

// Find all the output generated by genrules. Should really only be 1:1.
// If "suffix_index" is set, output is compatible with FinxBySuffix().
ProvidedFromTarget ExtractGeneratedFromGenrule(const ParsedProject &project,
                                               std::ostream &info_out,
                                               bool suffix_index = false);

// Extract all package groups, mapping the bazel target (the package group)
// to the packages listed.
struct PackageGroup {
  std::vector<std::string_view> packages;  // package patterns
  std::vector<BazelTarget> includes;       // reference to other packages.
};
using PackageGroups = OneToOne<BazelTarget, PackageGroup>;
PackageGroups ExtractPackageGroups(const ParsedProject &project);

// Given a package group, resolve all the patterns that match. Follows
// includes recursively to get a comprehensive list of patterns.
std::vector<std::string_view> ResolvePackageGroupPatterns(
  const PackageGroups &all_groups, const BazelTarget &package_group);

// Returns a map from targets to all the files they provide. Looks
// at filegroups and genrules. The returned mapping are string_view that
// point to the original locaion in the project, so can be location extracted.
TargetProvidedFiles ExtractFilegroupTargets(const ParsedProject &project);

// Expand every element in the list that is a filegroup with the content
// of that filegroup; leave other elements as-is.
// The string_views in the list will always point to the original location
// in the project, so it is possible to trace these back to the original BUILD
// file.
// Returns 'true' if filegroups have been expanded.
bool ExpandFilegroupsInList(const BazelPackage &context_package,
                            const TargetProvidedFiles &filegropus,
                            std::vector<std::string_view> *list);

struct FindResult {
  std::string match;  // Found match. Different from query if fuzzy match.
  const absl::btree_set<BazelTarget> *target_set;
  int fuzzy_score = 0;  // 0 if exact match otherwise path element count.
};

// Find a set of target that fuzzily match the suffix of the given key.
// index is required to be generated with reverse keys, i.e. "reverse_index"
// set to true when generating.
// If there is no full match, "min_fuzzy_path" selects the minimum number of
// path components that need to match. E.g. a match of foo/bar/baz.h would be 3.
std::optional<FindResult> FindBySuffix(const ProvidedFromTargetSet &index,
                                       std::string_view key,
                                       size_t min_fuzzy_paths = 2);

// Pretty-print provided files and targets they are coming from in two columns.
void PrintProvidedSources(Session &session, const std::string &table_header,
                          const BazelTargetMatcher &filter,
                          const ProvidedFromTarget &provided_from_lib);

void PrintProvidedSources(Session &session, const std::string &table_header,
                          const BazelTargetMatcher &filter,
                          const ProvidedFromTargetSet &provided_from_lib);

// Print filegroup-like set, mapping BazelTarget -> filestheyprovide*
// Makes files fully qualified
void PrintTargetFileSet(Session &session, const BazelWorkspace &workspace,
                        const BazelTargetMatcher &filter,
                        const TargetProvidedFiles &target_to_files);

// Print OneToN package group to list of patterns (cave: currently the table
// header writes 'pattern')
void PrintTargetToN(Session &session, const BazelWorkspace &workspace,
                    const BazelTargetMatcher &filter,
                    const PackageGroups &pkg_groups);

void PrintFileToFileSet(Session &session,
                        const HeaderToCanonicalHeader &header_to_headers);

}  // namespace bant

#endif  // BANT_PROJECT_INDEXING_
